postgresql:
  postgresqlPassword: postgres
  postgresqlDatabase: postgres
  service:
    type: NodePort
    nodePort: 31431

namespace: retail
DB_HOST: order-test-release-postgresql
DB_PORT: 5432
POSTGRES_DB: postgres
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
