/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.prapps.retail.management.order;

import com.prapps.retail.management.order.service.OrderService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;
import org.springframework.context.annotation.Profile;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.stereotype.Component;

import java.util.Collections;

@EnableFeignClients
@EnableJpaRepositories
@SpringBootApplication
@Profile("!test")
public class OrderApp {

    public static void main(String[] args) {
        SpringApplication.run(OrderApp.class, args);
    }

    @Component
    public class ApplicationRunner implements CommandLineRunner {
        @Autowired
        OrderService customerService;
        @Override
        public void run(String... args) {
            Order order = new Order();
            order.setCustomerId(1L);
            OrderProduct orderProduct = new OrderProduct();
            orderProduct.setProductId(1L);
            orderProduct.setQuantity(3);
            order.setOrderProducts(Collections.singleton(orderProduct));
            Order savedOrder = customerService.create(order);
            System.out.println("OrderId: "+savedOrder.getId());
        }
    }
}
