/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.prapps.retail.management.product;

import com.prapps.retail.management.messaging.service.MessagingService;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.junit.jupiter.SpringExtension;


@ExtendWith(SpringExtension.class)
@SpringBootTest
@ActiveProfiles("test")
public class MessagingAppTest {
    @Autowired
    MessagingService messagingService;


}
