/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.prapps.retail.management.product;

import com.prapps.retail.management.messaging.service.ProductService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.stereotype.Component;

@EnableJpaRepositories
@SpringBootApplication
public class ProductApp {

    public static void main(String[] args) {
        SpringApplication.run(ProductApp.class, args);
    }

    @Component
    public class ApplicationRunner implements CommandLineRunner {
        @Autowired
        ProductService productService;
        @Override
        public void run(String... args) {
            Product product = new Product(null, "test_category", "test desc");
            Product savedProduct = productService.create(product);
            System.out.println("ProductId: "+savedProduct.getId());
        }
    }
}
