server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: update


#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE


customerApp.url: ${CUSTOMER_APP.URL:http://localhost:8081/customer}
productApp.url: ${PRODUCT_APP.URL:http://localhost:8082/product}