#kafka:
#  external:
#    enabled: true
#    type: NodePort
#  configurationOverrides:
#    advertised.listeners: |-
#      EXTERNAL://kafka.cluster.local:$((31090 + ${KAFKA_BROKER_ID}))
#    listener.security.protocol.map: |-
#      PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT

postgresql:
  postgresqlPassword: postgres
  postgresqlDatabase: postgres
  service:
    type: NodePort
    nodePort: 31432

namespace: retail
DB_HOST: product-test-release-postgresql
DB_PORT: 5432
POSTGRES_DB: postgres
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
