/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.prapps.retail.management.product;

import com.prapps.retail.management.customer.Customer;
import com.prapps.retail.management.customer.CustomerApp;
import com.prapps.retail.management.customer.service.CustomerService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;


@ExtendWith(SpringExtension.class)
@SpringBootTest(classes = CustomerApp.class)
public class CustomerAppTest {
    @Autowired
    CustomerService customerService;

    @Test
    public void testCreateProduct() {
        String fName = "Pratik";
        String lName = "Sengupta";
        Customer customer = new Customer(null, fName, lName);
        Customer savedProduct = customerService.create(customer);
        Customer retrievedCustomer = customerService.findById(savedProduct.getId())
                .orElseThrow(AssertionError::new);
        assertEquals(fName, retrievedCustomer.getFirstName());
        assertEquals(lName, retrievedCustomer.getLastName());
    }
}
