spring:
  application:
    name: student-service
server:
  port: 8080

services:
  core-api:
    student-endpoint: ${CORE_API_HOST}/${CORE_API_STUDENT_ENDPOINT:rest/db/student}

logging:
  #file: ${logging.baseloc}/${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}.log
  level:
    root: INFO
#    org.springframework.web: DEBUG
    com.prapps: DEBUG
    com.pega: DEBUG
