apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
spec:
  replicas: 1
  selector:
      matchLabels:
        app: student-service
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
        - name: student-service-pod
          image: pratik006/student-service:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: CORE_API_HOST
            value: http://db-service.default:8080
          - name: CORE_API_STUDENT_ENDPOINT
            value: rest/db/student


---
apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  selector:
    app: student-service
  ports:
    - name: http
      protocol: TCP
      # Which port on the node is the service available through?
      nodePort: 32001
      # Inside the cluster, what port does the service expose?
      port: 8080
      # Which port do pods selected by this service expose?
      targetPort: 8080
  type: LoadBalancer