/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.prapps.retail.management.customer;

import com.prapps.retail.management.customer.service.CustomerService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.stereotype.Component;

@EnableJpaRepositories
@SpringBootApplication
public class CustomerApp {

    public static void main(String[] args) {
        SpringApplication.run(CustomerApp.class, args);
    }

    @Component
    public class ApplicationRunner implements CommandLineRunner {
        @Autowired
        CustomerService customerService;
        @Override
        public void run(String... args) {
            Customer customer = new Customer(null, "Pratik", "Sengupta");
            Customer savedCustomer = customerService.create(customer);
            System.out.println("CustomerId: "+savedCustomer.getId());
        }
    }
}
