/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.prapps.retail.management.messaging;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MessagingApp {
    public static void main(String[] args) {
        SpringApplication.run(MessagingApp.class, args);
    }
}
